/* Auto-generated by tiny_ml_compiler. Do not edit. */
#include "model.h"
#include "weight.h"

/* 交换两个 k2c_tensor 的全部内容（array 指针 + ndim/numel/shape），
   供 Dropout 等无操作层零成本传递数据。 */
static inline void k2c_tensor_swap(k2c_tensor *a, k2c_tensor *b) {
    k2c_tensor tmp = *a;
    *a = *b;
    *b = tmp;
}

/* 工作张量内存：按网络最大激活 25088、最大 same 填充 8192 分配 */
static float buf_a[25088] = {0};
static float buf_b[25088] = {0};
static float buf_pad[8192] = {0};
static k2c_tensor ta = {buf_a, 0, 0, {0,0,0,0,0}};
static k2c_tensor tb = {buf_b, 0, 0, {0,0,0,0,0}};
static k2c_tensor pad_work = {buf_pad, 0, 0, {0,0,0,0,0}};

/* 单样本前向推理。input 为调用方提供的输入张量，
   *output 指向最终结果所在的工作张量；返回 0 表示成功。 */
int forward(const k2c_tensor* input, k2c_tensor** output) {
    /* 归一化工作张量的 array 指针：层间 swap 会交换 ta/tb 的底层缓冲，
       每次进入 forward 时恢复映射，保证可重复调用。 */
    ta.array = buf_a;
    tb.array = buf_b;
    /* [0] conv2d: Conv2D (padding=same) */
    ta.ndim = 3; ta.numel = 25088;
    ta.shape[0]=28; ta.shape[1]=28; ta.shape[2]=32; ta.shape[3]=0; ta.shape[4]=0;
    pad_work.ndim = 3; pad_work.numel = 900;
    pad_work.shape[0]=30; pad_work.shape[1]=30; pad_work.shape[2]=1; pad_work.shape[3]=0; pad_work.shape[4]=0;
    k2c_pad2d(&pad_work, input, 0.0f, conv2d_padding);
    k2c_conv2d(&ta, &pad_work,
           &conv2d_kernel_tensor, &conv2d_bias_tensor,
           conv2d_stride, conv2d_dilation, conv2d_activation);

    /* [1] max_pooling2d: MaxPooling2D */
    tb.ndim = 3; tb.numel = 6272;
    tb.shape[0]=14; tb.shape[1]=14; tb.shape[2]=32; tb.shape[3]=0; tb.shape[4]=0;
    k2c_maxpool2d(&tb, &ta, max_pooling2d_pool_size, max_pooling2d_strides);

    /* [2] conv2d_1: Conv2D (padding=same) */
    ta.ndim = 3; ta.numel = 12544;
    ta.shape[0]=14; ta.shape[1]=14; ta.shape[2]=64; ta.shape[3]=0; ta.shape[4]=0;
    pad_work.ndim = 3; pad_work.numel = 8192;
    pad_work.shape[0]=16; pad_work.shape[1]=16; pad_work.shape[2]=32; pad_work.shape[3]=0; pad_work.shape[4]=0;
    k2c_pad2d(&pad_work, &tb, 0.0f, conv2d_1_padding);
    k2c_conv2d(&ta, &pad_work,
           &conv2d_1_kernel_tensor, &conv2d_1_bias_tensor,
           conv2d_1_stride, conv2d_1_dilation, conv2d_1_activation);

    /* [3] max_pooling2d_1: MaxPooling2D */
    tb.ndim = 3; tb.numel = 3136;
    tb.shape[0]=7; tb.shape[1]=7; tb.shape[2]=64; tb.shape[3]=0; tb.shape[4]=0;
    k2c_maxpool2d(&tb, &ta, max_pooling2d_1_pool_size, max_pooling2d_1_strides);

    /* [4] flatten: Flatten */
    k2c_flatten(&ta, &tb);

    /* [5] dense: Dense */
    tb.ndim = 1; tb.numel = 128;
    tb.shape[0]=128; tb.shape[1]=0; tb.shape[2]=0; tb.shape[3]=0; tb.shape[4]=0;
    k2c_dense(&tb, &ta,
          &dense_kernel_tensor, &dense_bias_tensor, dense_activation, NULL);

    /* [6] dropout: Dropout 推理无操作，交换工作张量传递数据 */
    k2c_tensor_swap(&ta, &tb);

    /* [7] dense_1: Dense */
    tb.ndim = 1; tb.numel = 10;
    tb.shape[0]=10; tb.shape[1]=0; tb.shape[2]=0; tb.shape[3]=0; tb.shape[4]=0;
    k2c_dense(&tb, &ta,
          &dense_1_kernel_tensor, &dense_1_bias_tensor, dense_1_activation, NULL);

    *output = &tb;
    return 0;
}
